# Generated by Django 4.1.9 on 2023-05-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
