# Generated by Django 4.1.9 on 2023-05-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='picture',
            field=models.ImageField(default='', upload_to='car_pictures/'),
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.voiture')),
            ],
        ),
    ]
