# Generated by Django 4.1.9 on 2023-05-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_voiture_picture_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(default='----', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='picture',
            field=models.ImageField(default='', upload_to='client_pictures/'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default='actif', max_length=100),
        ),
    ]
