# Generated by Django 4.1.9 on 2023-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='voiture',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='voiture',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], default='Gasoline', max_length=50),
        ),
        migrations.AddField(
            model_name='voiture',
            name='rental_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=8),
        ),
        migrations.AddField(
            model_name='voiture',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='voiture',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=50),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='make',
            field=models.CharField(default='', max_length=50),
        ),
    ]
