# Generated by Django 4.1.9 on 2023-05-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_reservation_status_delete_carreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='make',
            new_name='nom',
        ),
    ]
