# Generated by Django 4.1.9 on 2023-05-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_make_voiture_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='nom',
            new_name='make',
        ),
    ]
