# Generated by Django 4.1.9 on 2023-05-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_nom_voiture_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
