# Generated by Django 4.1.9 on 2023-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_reservation_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
