# Generated by Django 4.1.9 on 2023-05-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_voiture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='etat',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
