# Generated by Django 4.1.9 on 2023-05-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_reservation_etat_alter_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='available',
        ),
        migrations.CreateModel(
            name='NonAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.voiture')),
            ],
        ),
    ]
